#!/usr/bin/env bash
# One-time bootstrap for git-backed SQLite snapshots.
#
#   1. Create the private GitHub repo (idempotent — skips if it exists)
#   2. Init a local checkout at $BACKUP_REPO
#   3. Take an initial snapshot + push
#   4. Install the launchd job that runs backup.sh nightly
set -euo pipefail

BACKUP_REPO="${KM_BACKUP_REPO:-$HOME/Library/Application Support/keyboard-manager/git-backup}"
REPO_NAME="${KM_BACKUP_GH_REPO:-keyboard-stats-backup}"
GH_USER="$(gh api user --jq .login)"
REMOTE_URL="git@github.com:${GH_USER}/${REPO_NAME}.git"

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

log() { printf '%s %s\n' "$(date '+%H:%M:%S')" "$*"; }

# ── 1. GitHub repo ─────────────────────────────────────────────────────
if gh repo view "${GH_USER}/${REPO_NAME}" >/dev/null 2>&1; then
  log "✓ GitHub repo ${GH_USER}/${REPO_NAME} already exists"
else
  log "Creating private GitHub repo ${GH_USER}/${REPO_NAME}…"
  gh repo create "${GH_USER}/${REPO_NAME}" \
    --private \
    --description "keyboard-manager keystat snapshots — auto-committed by scripts/git-backup/backup.sh" \
    >/dev/null
  log "✓ repo created"
fi

# ── 2. Local checkout ──────────────────────────────────────────────────
if [[ -d "${BACKUP_REPO}/.git" ]]; then
  log "✓ local checkout already initialized at ${BACKUP_REPO}"
else
  # Probe whether the remote has any commits. A freshly-created (empty) repo
  # needs init+seed; an existing repo with history just needs clone.
  if gh api "repos/${GH_USER}/${REPO_NAME}/commits?per_page=1" --silent 2>/dev/null; then
    log "Cloning existing remote into ${BACKUP_REPO}…"
    git clone -q "${REMOTE_URL}" "${BACKUP_REPO}"
  else
    log "Initializing fresh local checkout at ${BACKUP_REPO}…"
    mkdir -p "${BACKUP_REPO}"
    cd "${BACKUP_REPO}"
    git init -q -b main
    git remote add origin "${REMOTE_URL}"

    # Seed with a README so the first push has content even before keystat.db
    # exists.
    cat > README.md <<EOF
# keyboard-manager keystat snapshots

Auto-generated by \`scripts/git-backup/backup.sh\` in
[\`${GH_USER}/keyboard-manager\`](https://github.com/${GH_USER}/keyboard-manager).
Do not edit by hand — every push is a new snapshot of the live SQLite file.
EOF
    git add README.md
    git -c user.email="${GH_USER}@users.noreply.github.com" \
        -c user.name="${GH_USER}" \
        commit -q -m "init: seed repo"
    git push -u origin main
    log "✓ initial push complete"
  fi
fi
cd "${BACKUP_REPO}"

# ── 3. First snapshot ──────────────────────────────────────────────────
log "Taking initial snapshot…"
bash "${PROJECT_ROOT}/scripts/git-backup/backup.sh" || log "(no live db yet — that's fine)"

# ── 4. launchd job ─────────────────────────────────────────────────────
log "Installing launchd job…"
bash "${PROJECT_ROOT}/scripts/git-backup/install-launchd.sh"

log "Done."
log "  - Repo:      https://github.com/${GH_USER}/${REPO_NAME}"
log "  - Local:     ${BACKUP_REPO}"
log "  - Schedule:  daily at 03:30 local (launchd will catch up if missed)"
log
log "Manual snapshot:   ./scripts/git-backup/backup.sh"
log "Uninstall:         ./scripts/git-backup/uninstall.sh"
